TRUNCATE WAREHOUSES, COMPANY, ITEMS;

insert into ITEMS (volume, name) values (32, 'box of screws');
insert into ITEMS (volume, name) values (12, 'bag of nails');
insert into ITEMS (volume, name) values (45, 'hammer');
insert into ITEMS (volume, name) values (33, 'screwdriver');
insert into ITEMS (volume, name) values (27, 'paintbrush');
insert into ITEMS (volume, name) values (32, 'roll of duct tape');
insert into ITEMS (volume, name) values (23, 'flashlight');
insert into ITEMS (volume, name) values (90, 'batteries');
insert into ITEMS (volume, name) values (75, 'extension cord');
insert into ITEMS (volume, name) values (25, 'tool box');
insert into ITEMS (volume, name) values (9, 'ladder');
insert into ITEMS (volume, name) values (44, 'bucket');
insert into ITEMS (volume, name) values (1, 'work gloves');
insert into ITEMS (volume, name) values (3, 'measuring tape');
insert into ITEMS (volume, name) values (24, 'pliers');
insert into ITEMS (volume, name) values (44, 'level');
insert into ITEMS (volume, name) values (8, 'safety goggles');
insert into ITEMS (volume, name) values (74, 'utility knife');
insert into ITEMS (volume, name) values (26, 'paint roller');
insert into ITEMS (volume, name) values (16, 'caulk gun');

insert into COMPANY (name) values ('Acme Corporation');
insert into COMPANY (name) values ('Widget Industries');
insert into COMPANY (name) values ('Starlight Enterprises');
insert into COMPANY (name) values ('Sunrise Solutions');
insert into COMPANY (name) values ('Peak Performance Inc.');

insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunset Storage', 1, 'Bojongloa', 6, 0, 46);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Mountain View Warehouse', 2, 'Palmas Bellas', 9, 0, 38);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Golden Gate Depot', 5, 'Cayur', 11, 0, 51);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Pine Valley Distribution Center', 1, 'Lopar', 19, 0, 32);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Oceanfront Logistics', 3, 'Jishan', 10, 0, 38);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Valley Vista Storage', 1, 'Qitan', 12, 0, 68);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Meadowbrook Warehouse', 5, 'Mailag', 4, 0, 87);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Silver Lake Depot', 5, 'Jingyang', 19, 0, 79);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Maple Grove Distribution Center', 3, 'San José de los Remates', 15, 0, 67);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverfront Logistics', 1, 'Altamira', 6, 0, 54);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunny Hills Storage', 4, 'Kimhae', 9, 0, 26);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Forest Ridge Warehouse', 1, 'Pulopaya', 11, 0, 82);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Harbor View Depot', 5, 'Nanyang', 20, 0, 93);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Springfield Distribution Center', 5, 'Puszczykowo', 3, 0, 82);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Lakeside Logistics', 2, 'Tovarnik', 9, 0, 32);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Hilltop Storage', 4, 'Gatesville', 19, 0, 92);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Cedar Creek Warehouse', 2, 'Villa Yapacaní', 9, 0, 57);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Willowbrook Depot', 2, 'Liudu', 5, 0, 83);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Prairie View Distribution Center', 4, 'Abade de Neiva', 12, 0, 91);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverside Logistics', 2, 'Sena', 4, 0, 31);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunrise Storage', 2, 'Franco da Rocha', 7, 0, 46);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Mountain Ridge Warehouse', 1, 'Genova', 15, 0, 40);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Golden Valley Depot', 1, 'Kedungdoro', 3, 0, 88);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Pine Ridge Distribution Center', 2, 'Panenjoan', 9, 0, 90);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Ocean View Logistics', 5, 'Choszczno', 12, 0, 72);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Valley Ridge Storage', 5, 'Kilifarevo', 11, 0, 37);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Meadow View Warehouse', 2, 'Ludvika', 10, 0, 68);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Silver Ridge Depot', 5, 'Angatel', 7, 0, 65);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Maple View Distribution Center', 4, 'Qiqin', 18, 0, 40);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('River View Logistics', 4, 'Bozhou', 13, 0, 88);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunny Ridge Storage', 2, 'Dajanrurung', 9, 0, 51);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Forest View Warehouse', 3, 'Akora', 11, 0, 62);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Harbor Ridge Depot', 2, 'Włosienica', 12, 0, 37);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Springfield View Distribution Center', 3, 'Barreiras', 7, 0, 80);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Lakeside Ridge Logistics', 1, 'Bus’k', 4, 0, 86);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Hilltop View Storage', 2, 'Shuiyin', 16, 0, 67);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Cedar Ridge Warehouse', 5, 'Añatuya', 9, 0, 57);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Willow View Depot', 3, 'Domalanoan', 11, 0, 70);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Prairie Ridge Distribution Center', 5, 'Houping', 13, 0, 40);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverside View Logistics', 1, 'Maracay', 9, 0, 37);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunset Ridge Storage', 3, 'Levashi', 17, 0, 80);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Mountain View Warehouse', 2, 'Sapiranga', 12, 0, 67);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Golden Gate Depot', 1, 'Kure', 15, 0, 50);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Pine Valley Distribution Center', 4, 'Damulog', 10, 0, 65);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Oceanfront Logistics', 2, 'Jammāl', 14, 0, 75);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Valley Vista Storage', 5, 'Soledad', 16, 0, 99);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Meadowbrook Warehouse', 3, 'Krajan Kidul Rojopolo', 7, 0, 81);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Silver Lake Depot', 4, 'Cabak Satu', 7, 0, 40);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Maple Grove Distribution Center', 5, 'Shazhou', 7, 0, 55);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverfront Logistics', 5, 'Lesozavodsk', 14, 0, 39);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunny Hills Storage', 1, 'Gunan', 17, 0, 93);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Forest Ridge Warehouse', 2, 'Novaya Chigla', 10, 0, 83);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Harbor View Depot', 1, 'Paso de los Libres', 5, 0, 49);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Springfield Distribution Center', 4, 'Gowarczów', 4, 0, 68);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Lakeside Logistics', 5, 'La Paz', 6, 0, 43);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Hilltop Storage', 5, 'Durham', 15, 0, 81);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Cedar Creek Warehouse', 3, 'Necochea', 15, 0, 39);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Willowbrook Depot', 2, 'Bayonne', 8, 0, 77);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Prairie View Distribution Center', 2, 'Pinheiro Machado', 4, 0, 94);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverside Logistics', 3, 'Biga', 17, 0, 97);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunrise Storage', 5, 'Pogonsili', 4, 0, 66);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Mountain Ridge Warehouse', 2, 'Taoshan', 16, 0, 98);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Golden Valley Depot', 3, 'Kpalimé', 18, 0, 56);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Pine Ridge Distribution Center', 2, 'Lazaro Cardenas', 18, 0, 66);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Ocean View Logistics', 1, 'Sjöbo', 13, 0, 47);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Valley Ridge Storage', 5, 'Strömsund', 3, 0, 84);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Meadow View Warehouse', 1, 'Guariba', 13, 0, 27);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Silver Ridge Depot', 5, 'Shetan', 14, 0, 67);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Maple View Distribution Center', 4, 'Ungheni', 18, 0, 78);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('River View Logistics', 1, 'Kepel', 18, 0, 46);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunny Ridge Storage', 1, 'Añelo', 9, 0, 94);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Forest View Warehouse', 5, 'Zheleznodorozhnyy', 20, 0, 83);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Harbor Ridge Depot', 1, 'Borlänge', 19, 0, 51);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Springfield View Distribution Center', 1, 'Sơn Tây', 9, 0, 58);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Lakeside Ridge Logistics', 5, 'Cangqian', 18, 0, 57);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Hilltop View Storage', 1, 'Zhenjiang', 4, 0, 64);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Cedar Ridge Warehouse', 5, 'Jinsha', 14, 0, 74);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Willow View Depot', 1, 'Al Jumūm', 17, 0, 94);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Prairie Ridge Distribution Center', 4, 'Pangal Sur', 7, 0, 70);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverside View Logistics', 4, 'Huaxijie', 8, 0, 60);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunset Storage', 2, 'Brak', 12, 0, 51);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Mountain View Warehouse', 3, 'Dongshan', 16, 0, 99);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Golden Gate Depot', 3, 'Tuusniemi', 9, 0, 60);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Pine Valley Distribution Center', 2, 'Ocaña', 20, 0, 87);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Oceanfront Logistics', 3, 'Hisor', 8, 0, 66);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Valley Vista Storage', 1, 'Wongsorejo', 16, 0, 41);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Meadowbrook Warehouse', 5, 'Citalahab', 12, 0, 32);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Silver Lake Depot', 4, 'Velké Meziříčí', 4, 0, 80);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Maple Grove Distribution Center', 1, 'Warugunung', 13, 0, 84);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverfront Logistics', 5, 'Novopavlovsk', 17, 0, 91);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Sunny Hills Storage', 5, 'Skwierzyna', 11, 0, 35);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Forest Ridge Warehouse', 3, 'Staraya Derevnya', 5, 0, 73);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Harbor View Depot', 5, 'Krasnoarmeysk', 15, 0, 54);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Springfield Distribution Center', 2, 'Rumphi', 17, 0, 31);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Lakeside Logistics', 3, 'Rosignol', 5, 0, 34);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Hilltop Storage', 3, 'Dois Vizinhos', 13, 0, 60);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Cedar Creek Warehouse', 2, 'Xihu', 5, 0, 62);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Willowbrook Depot', 3, 'Alīgūdarz', 19, 0, 44);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Prairie View Distribution Center', 4, 'Tongzha', 7, 0, 37);
insert into WAREHOUSES (name, company_id, location, item_id, holding, capacity) values ('Riverside Logistics', 3, 'Roissy Charles-de-Gaulle', 13, 0, 84);

-- INSERT into ADMINS (company_id, username, pass, authority) values (1, 'name1', 'pass1', 1);
-- INSERT into ADMINS (company_id, username, pass, authority) values (2, 'name2', 'pass2', 1);
-- INSERT into ADMINS (company_id, username, pass, authority) values (3, 'name3', 'pass3', 1);
-- INSERT into ADMINS (company_id, username, pass, authority) values (4, 'name4', 'pass4', 1);
-- INSERT into ADMINS (company_id, username, pass, authority) values (5, 'name5', 'pass5', 1);