DROP TABLE IF EXISTS COMPANY, WAREHOUSES, ITEMS;

CREATE TABLE ITEMS (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    VOLUME INT,
    NAME VARCHAR(50)
);

CREATE TABLE COMPANY (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50)
);

-- CREATE TABLE ADMINS (
--     ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
--     COMPANY_ID INT,
--     USERNAME VARCHAR(20),
--     PASS VARCHAR(20),
--     AUTHORITY INT,
--     FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
-- );

CREATE TABLE WAREHOUSES (
    ID INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    NAME VARCHAR(50),
    COMPANY_ID INT,
    LOCATION VARCHAR(50),
    ITEM_ID INT,
    HOLDING INT /*CHECK (HOLDING > 0 AND HOLDING < CAPACITY)*/,
    CAPACITY INT /*CHECK (CAPACITY > 0)*/,
    FOREIGN KEY (ITEM_ID) REFERENCES ITEMS(ID),
    FOREIGN KEY (COMPANY_ID) REFERENCES COMPANY(ID)
);
