truncate warehouses;

insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (1, 'Dougie', 2, 'toronto', 17, 53, 78);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (2, 'Lindsy', 4, 'ivory coast', 2, 34, 63);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (3, 'Brianna', 3, 'pittsburgh', 8, 75, 94);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (4, 'Conrado', 5, 'pittsburgh', 7, 29, 81);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (5, 'Lorri', 5, 'san antonio', 11, 43, 65);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (6, 'Gael', 1, 'toronto', 7, 12, 70);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (7, 'Chico', 2, 'new york', 5, 1, 96);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (8, 'Ketty', 4, 'toronto', 15, 64, 77);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (9, 'Worthington', 4, 'los angeles', 10, 37, 27);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (10, 'Patsy', 5, 'pittsburgh', 10, 70, 9);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (11, 'Gretna', 3, 'alberta', 16, 74, 48);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (12, 'Jasmina', 3, 'alberta', 20, 81, 97);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (13, 'Westleigh', 4, 'los angeles', 8, 14, 6);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (14, 'Corri', 5, 'panama', 1, 43, 47);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (15, 'Christi', 5, 'toronto', 5, 34, 40);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (16, 'Aldrich', 5, 'new york', 19, 32, 76);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (17, 'Jud', 5, 'toronto', 15, 53, 45);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (18, 'Iolanthe', 2, 'los angeles', 16, 91, 93);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (19, 'Lamont', 4, 'new york', 14, 35, 1);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (20, 'Nellie', 3, 'honduras', 9, 24, 18);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (21, 'Gerek', 1, 'honduras', 16, 58, 50);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (22, 'Rockie', 4, 'pittsburgh', 1, 44, 53);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (23, 'Engelbert', 4, 'rio', 1, 18, 5);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (24, 'Angeli', 3, 'new york', 8, 72, 57);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (25, 'Alford', 4, 'new york', 2, 38, 53);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (26, 'Ellette', 3, 'toronto', 15, 36, 80);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (27, 'Phillip', 2, 'alberta', 11, 100, 82);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (28, 'Mikel', 2, 'philly', 12, 80, 57);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (29, 'Athena', 5, 'toronto', 1, 55, 40);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (30, 'Filbert', 4, 'alberta', 15, 97, 96);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (31, 'Avrit', 5, 'panama', 2, 79, 34);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (32, 'Stephani', 5, 'toronto', 10, 76, 88);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (33, 'Raymund', 5, 'beijing', 8, 12, 98);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (34, 'Magdalene', 4, 'ho chi minh', 6, 83, 93);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (35, 'Leonelle', 3, 'ho chi minh', 2, 70, 29);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (36, 'Betta', 3, 'san antonio', 16, 59, 9);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (37, 'Frederich', 4, 'beijing', 6, 30, 4);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (38, 'Estelle', 3, 'philly', 6, 100, 87);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (39, 'Renate', 2, 'alberta', 1, 47, 58);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (40, 'Anjanette', 1, 'new york', 3, 49, 49);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (41, 'Yoshi', 1, 'new york', 20, 9, 22);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (42, 'Paige', 1, 'philly', 13, 59, 4);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (43, 'Eldon', 5, 'rio', 10, 31, 2);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (44, 'Darcee', 1, 'ho chi minh', 18, 79, 76);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (45, 'Elsinore', 3, 'toronto', 19, 47, 73);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (46, 'Charline', 3, 'los angeles', 16, 67, 72);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (47, 'Jodi', 2, 'rio', 15, 22, 77);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (48, 'Ryon', 3, 'toronto', 3, 78, 97);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (49, 'Biddie', 2, 'honduras', 19, 55, 76);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (50, 'Ricki', 3, 'beijing', 9, 100, 96);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (51, 'Nataline', 2, 'rio', 17, 7, 41);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (52, 'Gonzales', 2, 'rio', 6, 13, 17);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (53, 'Petrina', 1, 'san antonio', 10, 89, 85);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (54, 'Kayla', 1, 'toronto', 15, 83, 45);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (55, 'Nikaniki', 3, 'new york', 16, 39, 100);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (56, 'Ranice', 3, 'philly', 14, 41, 17);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (57, 'Fidelity', 3, 'new york', 11, 39, 53);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (58, 'Vi', 4, 'los angeles', 16, 80, 16);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (59, 'Vere', 3, 'rio', 11, 95, 19);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (60, 'Christal', 5, 'san antonio', 6, 33, 41);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (61, 'Daven', 5, 'beijing', 4, 51, 4);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (62, 'Esther', 1, 'philly', 18, 78, 40);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (63, 'Lionello', 3, 'panama', 10, 30, 4);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (64, 'Hermy', 3, 'san antonio', 4, 18, 62);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (65, 'Skyler', 5, 'los angeles', 16, 50, 99);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (66, 'Fan', 2, 'philly', 8, 46, 34);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (67, 'Kacie', 4, 'panama', 13, 91, 4);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (68, 'Terrel', 3, 'toronto', 5, 89, 69);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (69, 'Shadow', 4, 'alberta', 12, 52, 91);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (70, 'Jeanne', 2, 'toronto', 17, 21, 50);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (71, 'Gerhard', 2, 'ivory coast', 10, 40, 27);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (72, 'Theodor', 3, 'philly', 13, 30, 20);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (73, 'Elke', 1, 'panama', 8, 13, 91);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (74, 'Marylee', 3, 'los angeles', 2, 95, 57);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (75, 'Padraic', 3, 'honduras', 20, 39, 17);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (76, 'Janette', 5, 'panama', 17, 12, 29);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (77, 'Roxy', 5, 'beijing', 18, 23, 5);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (78, 'Tessi', 1, 'new york', 10, 95, 57);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (79, 'Darb', 2, 'los angeles', 18, 10, 63);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (80, 'Nessa', 4, 'rio', 4, 91, 47);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (81, 'Dorian', 5, 'toronto', 6, 30, 79);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (82, 'Madlin', 4, 'ivory coast', 18, 61, 12);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (83, 'Lurette', 3, 'panama', 5, 21, 54);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (84, 'Parker', 1, 'san antonio', 7, 76, 59);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (85, 'Terry', 4, 'toronto', 6, 18, 39);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (86, 'Reamonn', 3, 'beijing', 14, 2, 8);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (87, 'Nelle', 5, 'ho chi minh', 9, 45, 63);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (88, 'Thomasine', 5, 'pittsburgh', 7, 12, 95);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (89, 'Simonette', 2, 'pittsburgh', 13, 72, 71);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (90, 'Linnet', 5, 'beijing', 7, 61, 78);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (91, 'Salim', 1, 'rio', 9, 42, 19);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (92, 'Kissee', 5, 'panama', 4, 58, 42);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (93, 'Kelci', 4, 'rio', 18, 76, 73);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (94, 'Hedy', 2, 'alberta', 7, 38, 30);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (95, 'Robinia', 3, 'panama', 11, 6, 81);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (96, 'Clerc', 1, 'panama', 12, 74, 51);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (97, 'Adelice', 4, 'ivory coast', 17, 73, 86);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (98, 'Brew', 3, 'pittsburgh', 9, 16, 31);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (99, 'Daron', 2, 'los angeles', 5, 62, 19);
insert into WAREHOUSES (id, Name, company_id, location, item_id, holding, capacity) values (100, 'Agathe', 4, 'toronto', 1, 62, 35);
